### ISSUE TITLE
Вынесьти конфиги наружу докер-образа

### ISSUE THREAD

**Issue by pelid** [devmanorg/wttr.in#4]
Файл `.wegorc` в репозитории содержит ключ для доступа к провайдеру worldweatheronline.com. Это чувствительные данные и хотелось бы передавать их при запуске docker-контейнера либо через переменные окружения, либо через volume.

Та же история с `.ip2location.key`.

Помимо этого, есть проблемы с файлами справочников airports.dat и GeoLite2-City.mmdb.

Если вынесьти их всех в volumes, то стоит добавить в репозиторий файл docker-compose.yaml для быстрой насройки и запуска. Выглядеть может так:

```yaml
version: "3.3"
services:
  wttr:
    build: wttr.in/
    ports:
      - "8002:8002"
    volumes:
      - ./.wegorc:/root/.wegorc
      - ./.ip2location.key:/root/.ip2location.key
      - ./airports.dat:/app/airports.dat
      - ./GeoLite2-City.mmdb:/app/GeoLite2-City.mmdb
```
